services:
  - type: web
    name: discord-trading-bot
    env: python
    runtime: python-3.11.0
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /health
    envVars:
      - key: DISCORD_TOKEN_PART1
        sync: false
      - key: DISCORD_TOKEN_PART2
        sync: false
      - key: DISCORD_CLIENT_ID_PART1
        sync: false
      - key: DISCORD_CLIENT_ID_PART2
        sync: false
      - key: METAAPI_TOKEN
        sync: false
      - key: MT5_ACCOUNT_ID
        sync: false